---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по
    ключевому слову или категории.
  - Требование 2 Пользователь должен иметь возможность фильтровать товары по
    цене, цвету, размеру и т.д.
  - Требование 3 Сайт должен иметь мобильную версию.
  - Требование 4 Пользователь должен иметь возможность просматривать товары и
    просматривать подробную информацию о товаре
  - Требование 5 Пользователь должен иметь возможность добавлять товары в
    корзину и просматривать содержимое корзины.
  - Требование 6 Сайт должен быть доступен на различных устройствах
non-functional:
  - Требование 7 Веб-сайт должен быть разработан с учетом удобства использования
    и оптимизирован для скорости работы.
  - Требование 8: Сайт должен быть безопасным и защищать данные пользователя.
  - Требование 9 Сайт должен быть протестирован на совместимость с последними
    версиями браузеров.
  - Требование 10 Сайт должен быть способен обрабатывать большое количество
    трафика.
implicit:
  - Требование 11 Кнопка «в корзину» должна быть одинакового размера на всех
    карточках товара.
  - Требование 12 Цена товара в русской версии должна отображаться в рублях.
  - Требование 13 Количество товара на главной странице русской версии должно
    отображаться в штуках(шт).
  - Требование 14 Кнопка «в корзину» не должна закрывать текст карточки товара.
  - Требование 15 После успешного оформления заказа должен происходить переход
    на страницу оплаты.
  - Требование 16 При нажатии на кнопку «в корзину» должно отображаться
    сообщение о добавлении товара в корзину.
